### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by rchrdlln** [jbrew/pt-voicebox#23]
Error I'm getting:

Traceback (most recent call last):
  File "bin/voicebox", line 10, in <module>
    vb = voicebox.Voicebox()
  File "/Users/fullname/code/pt-voicebox/voicebox/voicebox.py", line 69, in __init__
    self.load_voices()
  File "/Users/fullname/code/pt-voicebox/voicebox/voicebox.py", line 291, in load_voices
    self.add_voice()
  File "/Users/fullname/code/pt-voicebox/voicebox/voicebox.py", line 309, in add_voice
    new_voice.add_corpus(Corpus(text, corpus_name), corpus_weight)
  File "/Users/fullname/code/pt-voicebox/voicebox/corpus.py", line 31, in __init__
    self.make_tree()
  File "/Users/fullname/code/pt-voicebox/voicebox/corpus.py", line 50, in make_tree
    sentences = self.get_sentences()
  File "/Users/fullname/code/pt-voicebox/voicebox/corpus.py", line 100, in get_sentences
    ) for sentence in sentences if sentence]
  File "/Users/fullname/code/pt-voicebox/voicebox/corpus.py", line 100, in <listcomp>
    ) for sentence in sentences if sentence]
AttributeError: 'str' object has no attribute 'decode'

I'm using Python 3.5 - I think the problem is that the string in question is already decoded automatically by this point?

**Comment by blinry** [comment]
I also get this error after loading a corpus and entering a weight. Python 3.6.0.

**Comment by keilin** [comment]
FWIW, I had the same problem but it works if you use python2.7
