### ISSUE TITLE
Can't get attribute 'Voicebox' on <module '__main__' from 'bin/voicebox'>

### ISSUE THREAD

**Issue by blinry** [jbrew/pt-voicebox#25]
Using Python 3.6.0 and nose 1.3.7:

```
$ bin/voicebox 
Load previous session? y/n
y
1 howl_richard.pkl
Enter the number of the session you want to load:
1
Traceback (most recent call last):
  File "bin/voicebox", line 10, in <module>
    vb = voicebox.Voicebox()
  File "/home/seb/tmp/pt-voicebox/voicebox/voicebox.py", line 59, in __init__
    loaded_voicebox = self.load_session()               # unpickles a previously-saved object
  File "/home/seb/tmp/pt-voicebox/voicebox/voicebox.py", line 228, in load_session
    return loadobject(path)
  File "/home/seb/tmp/pt-voicebox/voicebox/pickler.py", line 15, in loadobject
    obj = pickle.load(input)
AttributeError: Can't get attribute 'Voicebox' on <module '__main__' from 'bin/voicebox'>
```

**Comment by pagefusionux** [comment]
I'm also getting this same error -- and would love to see a solution! ;)

**Comment by victorkitov** [comment]
Might be because Voicebox class in the code is not declared before unpickling.
