### ISSUE TITLE
Error: No module named cPickle

### ISSUE THREAD

**Issue by rifkegribenes** [jbrew/pt-voicebox#27]
I'm following the instructions in 'Getting Started (Mac OS X)'. After step 7 (`bin/voicebox`) i'm getting an error. Code from my Terminal looks like this:

```
Fullname:pt-voicebox Fullname$ bin/voicebox
Traceback (most recent call last):
  File "bin/voicebox", line 8, in <module>
    import voicebox
  File "/Users/Fullname/Desktop/pt-voicebox/voicebox/__init__.py", line 3, in <module>
    from .voicebox import Voicebox
  File "/Users/Fullname/Desktop/pt-voicebox/voicebox/voicebox.py", line 16, in <module>
    from .pickler import loadobject, save_object
  File "/Users/Fullname/Desktop/pt-voicebox/voicebox/pickler.py", line 4, in <module>
    import six.moves.cPickle as pickle
ImportError: No module named cPickle
```

**Comment by rifkegribenes** [comment]
oops, just realized this question was answered in an earlier thread. i followed the instructions here: https://github.com/jbrew/pt-voicebox/issues/18#issuecomment-266318663 and this resolved it. leaving this up in case somebody else runs into this issue.
